no change     /users/rg/baygun/miniforge3/condabin/conda
no change     /users/rg/baygun/miniforge3/bin/conda
no change     /users/rg/baygun/miniforge3/bin/conda-env
no change     /users/rg/baygun/miniforge3/bin/activate
no change     /users/rg/baygun/miniforge3/bin/deactivate
no change     /users/rg/baygun/miniforge3/etc/profile.d/conda.sh
no change     /users/rg/baygun/miniforge3/etc/fish/conf.d/conda.fish
no change     /users/rg/baygun/miniforge3/shell/condabin/Conda.psm1
no change     /users/rg/baygun/miniforge3/shell/condabin/conda-hook.ps1
no change     /users/rg/baygun/miniforge3/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /users/rg/baygun/miniforge3/etc/profile.d/conda.csh
no change     /users/rg/baygun/.bashrc
No action taken.

 N E X T F L O W   ~  version 24.10.3

Launching `main.nf` [tiny_fermat] DSL2 - revision: 982c432224

[-        ] NanoPlot -

[-        ] NanoPlot -
ERROR ~ Error executing process > 'NanoPlot (2)'

Caused by:
  No such variable: sample_name -- Check script 'main.nf' at line: 12


Source block:
  """
  sample_name = input_bam.baseName
  mkdir -p "result_nanoplot/${sample_name}"
  NanoPlot --ubam "${input_bam}" -o $output --N50 -threads 4
  """

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

[-        ] NanoPlot -
ERROR ~ Error executing process > 'NanoPlot (2)'

Caused by:
  No such variable: sample_name -- Check script 'main.nf' at line: 12


Source block:
  """
  sample_name = input_bam.baseName
  mkdir -p "result_nanoplot/${sample_name}"
  NanoPlot --ubam "${input_bam}" -o $output --N50 -threads 4
  """

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

