no change     /users/rg/baygun/miniforge3/condabin/conda
no change     /users/rg/baygun/miniforge3/bin/conda
no change     /users/rg/baygun/miniforge3/bin/conda-env
no change     /users/rg/baygun/miniforge3/bin/activate
no change     /users/rg/baygun/miniforge3/bin/deactivate
no change     /users/rg/baygun/miniforge3/etc/profile.d/conda.sh
no change     /users/rg/baygun/miniforge3/etc/fish/conf.d/conda.fish
no change     /users/rg/baygun/miniforge3/shell/condabin/Conda.psm1
no change     /users/rg/baygun/miniforge3/shell/condabin/conda-hook.ps1
no change     /users/rg/baygun/miniforge3/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /users/rg/baygun/miniforge3/etc/profile.d/conda.csh
no change     /users/rg/baygun/.bashrc
No action taken.

 N E X T F L O W   ~  version 24.10.3

Launching `main.nf` [curious_almeida] DSL2 - revision: f3235adf22

[-        ] NanoPlot -
ERROR ~ Error executing process > 'NanoPlot (3)'

Caused by:
  No such variable: sample_name -- Check script 'main.nf' at line: 10


Source block:
  """
  sample_name = input_bam.baseName
  mkdir -p "result_nanoplot/${sample_name}"
  NanoPlot --ubam "${input_bam}" -o result_nanoplot/${sample_name} --N50 -threads 4
  """

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

[-        ] NanoPlot -
ERROR ~ Error executing process > 'NanoPlot (3)'

Caused by:
  No such variable: sample_name -- Check script 'main.nf' at line: 10


Source block:
  """
  sample_name = input_bam.baseName
  mkdir -p "result_nanoplot/${sample_name}"
  NanoPlot --ubam "${input_bam}" -o result_nanoplot/${sample_name} --N50 -threads 4
  """

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

